// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahyznsgfflibdtwwuwpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeXpuc2dmZmxpYmR0d3d1d3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDYyNDQsImV4cCI6MjA2MzgyMjI0NH0.NmQqdcWhbIEloZh3FF7pPxR-xwFBa_kV3O5TtHLewDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);